language: php

php: 
  - 5.4
  - 5.5

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction  

script: 
 - phpunit --coverage-clover=coverage.clover
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
