language: php

php: 
  - 5.4
  - 5.5

before_script:
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install --dev --no-interaction  

script: phpunit -c .travis-phpunit.xml
